### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tanj** [yodalee/simplelang#1]
I was wondering if you would be willing license to this repo with some sort of open source license. I was thinking about using some of this code as the basis of my own language parser, but I can't in good conscience do that without a license.

Thanks.

**Comment by yodalee** [comment]
Sorry for the late reply (I never expect that someone will reply to my repository :P ). I think it is fine to use it.
I will add a MIT license I think.

**Comment by yodalee** [comment]
Solved with PR #2.
